apiversion: apps/v1
kind: Deployment
metadata:
  name: ashukubercluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ashukubercluster
  template:
    metadata:
      labels:
        app: ashukubercluster
    spec:
      containers:
      - name: ashukubercluster
        image: ashuregistry.azurecr.io/ashukubercluster
        ports:
        - containerPort: 80